version: '3'
services:
        web:
                image: flask_opps_v1
                build: .
                ports:
                        - "8342:8342"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
